version: '3.8'
services:
  db:
    container_name: java_features
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD : postgres
      PGDATA : /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/data/postgres
      - ./docker/local/postgres:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local