logging:
  level:
    root: INFO

appconfig:
  version: 0.0.1

bugsnag:
  api_key: test

micrometer:
  enabled: true
  prefix: procore.ecommerce-product-catalog-service

management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: 'health,loggers'
  endpoint:
    loggers.enabled: true
    health:
      enabled: true
      probes.enabled: true
  metrics:
    use-global-registry: false
    export.defaults.enabled: false

spring:
  liquibase:
    change-log: classpath:db/db.changelog-1.0.0.yml
    enabled: true
    contexts: development
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
    open-in-view: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/java_features
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

